---

- src: git@git-service.ait.ac.at:sct-cyberrange/ansible-roles/mariadb.git
  path: /etc/ansible/roles/cyber-range/mariadb
  scm: git
  version: master
  name: mariadb

- src: https://github.com/GROG/ansible-role-user.git
  scm: git
  version: master
  name: grog.user