---
- name: Ensure python and pip is installed
  become: true
  ansible.builtin.apt:
    name: 
      - python3
      - python3-venv
      - python3-pip
      - python3-requests 
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install pip modules
  become: true
  ansible.builtin.pip:
    name: 
      - mattermostdriver
      - pyyaml
    virtualenv: "{{ mattermost_basepath }}/venv"
    virtualenv_command: python3 -m venv
  
- name: Deploy mattermost init script
  become: true
  ansible.builtin.template:
    src: "{{ mattermost_init_script_src }}"
    dest: "{{ mattermost_basepath }}/init.py"
    owner: root
    group: root
    mode: "+x"

- name: Copy mattermost user config
  become: true
  ansible.builtin.copy:
    src: "{{ mattermost_init_config_src }}"
    dest: "{{ mattermost_basepath }}/init.yml"
    mode: "644"
    remote_src: "{{ mattermost_init_config_remote_source }}"

- name: Ensure mattermost is running
  become: true
  ansible.builtin.service:
    name: mattermost
    state: started
    enabled: true

- name: Run init script
  become: true
  ansible.builtin.command:
    cmd: "{{ mattermost_basepath }}/venv/bin/python3 {{ mattermost_basepath }}/init.py"
