---
- name: Install PostgreSQL and its dependencies
  become: true
  ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
      cache_valid_time: 3600
  loop:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Start and enable PostgreSQL service
  become: true
  ansible.builtin.service:
      name: postgresql
      enabled: true
      state: started

# postgres://mmuser:<mmuser-password>@<host-name-or-IP>:5432/mattermost?sslmode=disable&connect_timeout=10

- name: Create a PostgreSQL database and user
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
      name: '{{ mattermost_database_name }}'
      # owner: '{{ mattermost_database_user }}'
      # login_host: localhost
      # login_user: '{{ mattermost_service_user }}'
      # login_password: '{{ mattermost_service_user_password }}'

- name: Set PostgreSQL password for the user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
      name: '{{ mattermost_database_user }}'
      password: '{{ mattermost_database_user_password}}'
      # priv: ALL
      # db: '{{ mattermost_database_name }}'
      # login_host: localhost
      # login_user: '{{ mattermost_service_user }}'
      # login_password: '{{ mattermost_service_user_password }}'

- name:
      GRANT ALL PRIVILEGES ON DATABASE {{ mattermost_database_name }} TO {{
      mattermost_database_user }}
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
      db: postgres
      privs: ALL
      type: database
      obj: '{{ mattermost_database_name }}'
      role: '{{ mattermost_database_user }}'

- name: GRANT ALL PRIVILEGES ON SCHEMA PUBLIC TO {{ mattermost_database_user }}
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
      db: '{{ mattermost_database_name }}'
      privs: ALL
      type: schema
      objs: public
      role: '{{ mattermost_database_user }}'

- name: Get PostgreSQL version
  command: 'pg_config --version'
  register: postgres_version

- name: Change authentication methods to "trust"
  become: true
  ansible.builtin.replace:
      path:
          "/etc/postgresql/{{ postgres_version.stdout_lines |
          regex_search('(\\d+)\\.') | int }}/main/pg_hba.conf"
      regexp: '(^host|local)(.+)(md5|peer)(.*)$'
      replace: '\1\2trust\4'
      backup: true
  notify: Reload postgres
# - name: Install dependency packages
#   apt:
#     name: "{{item}}"
#     state: installed
#   with_items:
#     - 'icinga2-ido-pgsql'
#     - 'python-psycopg2'

# - name: Add database for mattermost
#   postgresql_db:
#     name: "{{ mattermost_database_name }}"
#   become_user: postgres

# - name: Add mattermost database user
#   postgresql_user:
#     name: "{{ mattermost_database_user }}"
#     password: "{{ mattermost_database_password }}"
#     db: "{{ mattermost_database_name }}"
#   become_user: postgres
