---

# - name: Ensure <{{ mm_packages | join(', ') }}> is installed
#   ansible.builtin.package:
#     name: "{{ mm_packages }}"
#     state: latest
#     update_cache: yes
#   become: yes

- name: "Install mattermost {{ mattermost_version | default('6.1.0') }}"
  ansible.builtin.unarchive:
    src: "https://releases.mattermost.com/\
      {{ mattermost_version | default('6.1.0') }}/\
      mattermost-{{ mattermost_version | default('6.1.0') }}-linux-amd64.tar.gz"
    dest: "{{ mm_paths.base }}/../"
    group: "{{ mattermost_user.group }}"
    remote_src: yes
  become: yes
  become_user: "{{ mattermost_user.name }}"

- name: "Ensure data directory exist"
  ansible.builtin.file:
    path: "{{ mm_paths.base }}/data"
    owner: "{{ mattermost_user.name }}"
    group: "{{ mattermost_user.group }}"
    state: directory
  become: yes

- name: Copy config file
  ansible.builtin.template:
    src: "mattermost_config.json.j2"
    dest: "{{ mm_paths.base }}/config/config.json"
    owner: "{{ mattermost_user.name }}"
    group: "{{ mattermost_user.group }}"
    mode: '0644'
  become: yes
