---
- name: Install Postgres
  ansible.builtin.include_tasks: database.yml

- name: Install mattermost
  ansible.builtin.include_tasks: mattermost.yml

- name: Install and configure nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Configure mattermost
  ansible.builtin.include_tasks: config.yml
