---
# tasks file for ansible-mattermost

# -------------------------------------------
# *** Add users ***
# -------------------------------------------

- name: "Ensure group {{ mattermost_user.group }} exists"
  ansible.builtin.group:
    name: "{{ mattermost_user.group }}"
    state: present
  become: yes

- name: "Ensure user {{ mattermost_user.name }} exists"
  ansible.builtin.include_role:
    name: grog.user
    apply:
      become: yes
  vars:
    user_list:
    - name: "{{ mattermost_user.name }}"
      groups: ["{{ mattermost_user.group }}"]


- name: "Ensure {{ mm_paths }}'s paths exist"
  ansible.builtin.file:
    path: "{{ item.value }}"
    owner: "{{ mattermost_user.name }}"
    group: "{{ mattermost_user.group }}"
    state: directory
  become: yes
  loop: "{{ mm_paths | dict2items }}"

# -------------------------------------------
# *** Database ***
# -------------------------------------------

- name: Install mariadb and configure database
  include_tasks:
    file: mariadb.yml

# -------------------------------------------
# *** Install Mattermost ***
# -------------------------------------------

- name: Install mattermost
  include_tasks:
    file: install_mattermost.yml

# -------------------------------------------
# *** Service ***
# -------------------------------------------

- name: Setup service
  include_tasks:
    file: service.yml

# -------------------------------------------
# *** Configure Mattermost ***
# -------------------------------------------

- name: Configure mattermost
  include_tasks:
    file: configure_mattermost.yml