---
- name: Create mattermost installation dirs
  become: true
  ansible.builtin.file:
      name: '{{ mattermost_basepath }}'
      state: directory

- name: Download Mattermost repository setup script
  ansible.builtin.get_url:
      url: https://deb.packages.mattermost.com/repo-setup.sh
      dest: /tmp/repo-setup.sh

- name: Execute Mattermost repository setup script
  become: true
  ansible.builtin.command:
      cmd: 'sudo bash /tmp/repo-setup.sh mattermost'

- name: Update apt repo and install mattermost
  become: true
  ansible.builtin.apt:
      name: mattermost
      update_cache: true
      cache_valid_time: 3600

- name: Copying config to server
  become: true
  ansible.builtin.template:
      src: templates/mattermost_config.json.j2
      dest: /opt/mattermost/config/config.json
      owner: mattermost
      group: mattermost
      mode: '0600'
  notify: Restart and enable mattermost
#
# 1.
#
#
#

# - name: Download mattermost
#   get_url:
#       url: 'https://releases.mattermost.com/{{ mattermost_tar }}'
#       dest: /tmp/
#       checksum: '{{ mattermost_tar_checksum }}'

# - name: Unpack mattermost
#   unarchive:
#       src: '/tmp/{{ mattermost_tar }}'
#       dest: '{{ mattermost_basepath }}'
#       copy: no
#       extra_opts:
#           - '--strip-components=1'
#   args:
#       creates: '{{ mattermost_basepath }}/bin/mattermost'

# - name: Create symlink to this version
#   file:
#       state: link
#       dest: '{{ mattermost_basepath }}/current'
#       src: '{{ mattermost_basepath }}'
#   notify: restart mattermost

# - name: Add systemd unit file for Mattermost
#   template:
#       src: mattermost.service.j2
#       dest: /etc/systemd/system/mattermost.service
#   notify: reload systemd and restart mattermost

# - name: Create group for Mattermost
#   group:
#       name: '{{ mattermost_group }}'
#       system: true
#   when: mattermost_group_create

# - name: Create user for Mattermost
#   user:
#       name: '{{ mattermost_user }}'
#       group: '{{ mattermost_group }}'
#       system: yes
#       createhome: no
#   when: mattermost_user_create

# - name: Create data directory for mattermost
#   file:
#       state: directory
#       name: '{{ mattermost_data_root }}'
#       owner: '{{ mattermost_user }}'
#       group: '{{ mattermost_group }}'
