---
- name: Create mattermost installation dirs
  become: true
  ansible.builtin.file:
      name: '{{ mattermost_basepath }}'
      state: directory
      recurse: true

- name: Download Mattermost repository setup script
  ansible.builtin.get_url:
      url: https://deb.packages.mattermost.com/repo-setup.sh
      dest: /tmp/repo-setup.sh

- name: Execute Mattermost repository setup script
  become: true
  ansible.builtin.command:
      cmd: 'sudo bash /tmp/repo-setup.sh mattermost'

- name: Update apt repo and install mattermost
  become: true
  ansible.builtin.apt:
      name: mattermost={{ mattermost_version }}
      allow_downgrade: true
      update_cache: true
      cache_valid_time: 7200

- name: Copying config to server
  become: true
  ansible.builtin.template:
      src: templates/mattermost_config.json.j2
      dest: /opt/mattermost/config/config.json
      owner: mattermost
      group: mattermost
      mode: '0600'
  notify: Restart and enable mattermost