---
- name: Install Nginx
  become: true
  ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: true
      cache_valid_time: 7200

- name: Deploy nginx config
  become: true
  ansible.builtin.template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/conf.d/mattermost.conf
      owner: root
      group: root
      mode: '0600'
  notify: Restart nginx
