---
- name: Reload postgres
  become: true
  ansible.builtin.service:
      name: postgresql
      state: reloaded

- name: Restart and enable mattermost
  become: true
  ansible.builtin.service:
      name: mattermost
      state: restarted
      enabled: true

- name: Restart nginx
  become: true
  ansible.builtin.service:
      name: nginx
      state: restarted
